---
title: "Five-Year Career Plan"
output: html_document
---
<br/>
I am currently a third-year student in the Integrative Life Sciences – Behavioral and Statistical Genetics Ph.D. program at Virginia Commonwealth University (VCU). My graduate training has allowed me to cultivate my research interests in genetic and environmental influences on suicidal behavior and substance use disorders, while also gaining experience with teaching and mentorship. I have published six first-author papers, presented my work at numerous conferences, and completed two teaching assistantships (with a teaching internship in progress). Each of these experiences has further reinforced my interest in pursuing a faculty position with a combination of research and teaching responsibilities.\ 
<br/>

My long-term professional goals are to make meaningful contributions to the literature on suicidal behavior, encourage students’ interests in genetics, statistics, and mental health, and engage students as research collaborators. Accordingly, it will be critical for me to further develop my research, teaching, and mentorship abilities over the next five years. My specific short-term goals are to (1) build my confidence and abilities as an independent researcher, (2) diversify my knowledge of research methods and topics, (3) gain experience with formal classroom instruction, and (4) identify and obtain a faculty appointment that matches my professional interests and personal values.\
<br/>
**General Timeline**\
I passed my dissertation proposal in August of 2022 and expect to complete my Ph.D. in May of 2024. As a result, my dissertation research is my primary focus over the next 18 months. After degree completion, I intend to transition to a two- or three-year postdoctoral fellowship. I hope to identify a supportive mentor whose research interests complement my graduate work. If possible, I would also prefer to accept a position at an institution other than VCU, so I may be exposed to a new research environment. In the Summer of 2026 or 2027, I aim to begin a tenure-track faculty appointment. Each of these career stages will promote the development of skills needed to accomplish my short- and long-term career goals.\
<br/>
**Goal 1: Build my confidence and abilities as an independent researcher.**\
Crafting and executing a dissertation project will mature my abilities as an independent researcher. For my dissertation, I am expected to develop the research questions and analytic plan, execute the analyses, respond to issues as they arise, and clearly communicate my findings to committee members. In doing so, I anticipate that I will improve a number of research abilities, including creativity, problem-solving, time management, and oral and written communication. In addition, I will further expand my abilities to develop an independent line of research as a postdoctoral fellow. A postdoctoral fellowship will expose me to new methods and ideologies, allowing me to further clarify my interests and develop a programmatic line of research. As I continue to develop and execute independent research projects, I expect that my confidence in my abilities will continue to grow.\
<br/>
**Goal 2: Diversify my knowledge of research methods and topics.**\
During my time at VCU, I have become increasingly familiar with the literature on suicidal behavior and substance use disorders. I have employed a range of statistical methods in my work, including structural equation modeling, polygenic risk scoring, genomic structural equation modeling, the co-relative model, and biometrical models. However, a potential limitation of my graduate training is that I have little experience with data collection and wet lab experiments. In addition, I have somewhat limited knowledge of other psychiatric outcomes. Accordingly, I plan to select a postdoctoral fellowship that will complement my graduate training, either by exposing me to new methods (e.g., by joining a lab that is currently engaged in genetic data collection or works directly with biological samples) or new phenotypes. I do not wish to leave the suicide genetics field, but I would like to deepen my understanding of suicidality by gaining experience with a different methodological approach or by investigating how the etiology of suicide overlaps with major psychiatric disorders.\
<br/>
Across my roles as a graduate student, postdoctoral fellow, and faculty member, I can also diversify my knowledge by pursuing additional training. For example, I hope to participate in workshops (e.g., the Summer Institute in Statistical Genetics, the International Statistical Genetics Workshop), attend new conferences, and audit courses at my institution. Developing new research collaborations will be another way to discover novel approaches to or perspectives on my research area.\
<br/>
**Goal 3: Gain experience with formal instruction.**\
I have pursued numerous opportunities to engage with and mentor students during my graduate training. In my first year at VCU, I mentored a team of four undergraduate students as they developed and carried out a research project. I have also completed teaching assistantships with the Department of Focused Inquiry and the Department of Psychology at VCU, and I am currently serving as a teaching intern in the Department of Biological Sciences at the University of Mary Washington. Through each of these teaching experiences, I have had the opportunity to meet with students individually, host office hours and review sessions, and provide feedback on assignments. As a result, my abilities to mentor one-on-one and teach small groups of students have grown immensely. However, my experience with formal instruction is much more limited. I have given four guest lectures during my time at VCU but do not yet feel confident in my abilities to lead a semester-long course. As a result, I hope to obtain a postdoctoral fellowship that allows for teaching opportunities. In addition, when applying for a faculty position, I will consider the opportunities available for teaching development, such as centers to promote teaching excellence, availability of teaching mentors, or reduced instructional loads for new faculty.\
<br/>
**Goal 4: Identify and obtain a faculty appointment that matches my professional interests and personal values.**\
By developing my abilities as an independent researcher, diversifying my research portfolio, and gaining experience with formal instruction, I hope to position myself as a good candidate for a tenure-track faculty position. I would like to acquire a faculty position that provides a combination of research and teaching responsibilities, offers time and resources for research, allows for meaningful engagement with students, and permits work-life balance. The only way to accomplish my long-term professional goals – to make substantive contributions to the literature on suicidal behavior, encourage students’ interests in genetics, statistics, and mental health, and engage students as research collaborators – is to identify an institution whose values and priorities align with my own.