---
title: "Responsible Conduct of Research Statement"
output: html_document
---
<br/>

During my graduate studies at Virginia Commonwealth University (VCU), I completed a semester-long course on the responsible conduct of research. Topics addressed within this course included responsible authorship; data management and record-keeping; use of humans and animals in research; collaboration; scientific rigor and reproducibility; conflicts of interest in research; research misconduct; and societal responsibility. I have also received informal training in the responsible conduct of research through weekly meetings with my mentor, Dr. Edwards. Dr. Edwards is actively involved in data collection efforts at the Virginia Institute for Psychiatric and Behavioral Genetics (VIPBG), conducts secondary analyses of observational and registry-based data, and participates in international research consortia, including the Substance Use Disorder and Suicide Working Groups of the Psychiatric Genomics Consortium. Dr. Edwards has invited me to participate in these efforts during my time as a graduate student, which has generated conversations regarding data sharing, privacy of participants, authorship, and collaboration in research. Because our work involves highly sensitive information (including human genetic data and self-reported information on substance misuse and suicidal behavior), our group is particularly attentive to proper data management and participant confidentiality. \
<br/>
In addition, Dr. Edwards’ group is committed to transparency and reproducibility in research, and each of our projects is pre-registered using the Open Science Framework. Pre-registration requires the scientist to forward specific hypotheses and describe the sample, measures, and statistical methods that will be utilized in the project. Any deviations from the pre-registered analytic plan are documented and justified. The pre-registration process discourages exploration of the data before drafting the analytic plan, thereby ensuring that the analyst’s decisions are not consciously or unconsciously influenced by any patterns observed in the data. I have pre-registered each of my research projects at VCU, and the process has been extremely helpful for planning analyses and documenting my analytic decisions. \
<br/>
Finally, my area of research – genetic influences on suicidality and substance use disorders – has substantial public health impact, and I have become increasingly aware of my societal responsibility as a scientist throughout my graduate training. As an example, many genetic studies of mental health conditions are limited to individuals of European ancestry, which limits the generalizability of findings to individuals of other ancestral groups (e.g., African, East Asian) and has the potential to exacerbate health disparities. I have approached this concern in my own work by including individuals across ancestral groups when possible. However, in many cases, my studies have also been restricted to European ancestry individuals, which I acknowledge as a limitation in resulting publications. I also participate in broader efforts to enhance the generalizability of findings across populations: For the past two years, I have served as a member of the VIPBG Inclusion, Diversity, Equity, and Access (IDEA) Committee, which is committed to increasing the diversity of participants in research studies at our institute. My work with the IDEA Committee has further encouraged me to carefully consider the limitations of my research area and to be aware of how seemingly minor analytic decisions can have broader societal impact.
