---
title: "Research Statement"
output: html_document
---
<br/>
**Overview of Research Interests**\
As a psychiatric genetics researcher, I apply principles of both behavioral genetics and developmental psychology to investigate the development of alcohol use disorder (AUD) and suicidal behavior. My undergraduate and graduate training spans diverse disciplines, including biochemistry, developmental psychology, and statistical genetics. Correspondingly, my work integrates genetically-informed approaches with theoretical frameworks to better understand the etiology of psychiatric disorder. I find the study of familial influences on alcohol outcomes and suicidality to be particularly compelling, providing an opportunity to disentangle the roles of genetic variation, familial relationships, and environmental contexts that vary between families, such as neighborhood characteristics. The continuation of my research plan will reflect my interest in applying a variety of statistical methods and theoretical perspectives, while also facilitating opportunities to engage in undergraduate student mentorship.\
<br/>

**Past Work on Alcohol Problems and Suicidal Behavior**\
In 2018, I enrolled in the Developmental Psychology Program at Virginia Commonwealth University, where I conducted research on genetic and environmental influences on AUD and fostered my interest in the contribution of familial relationships to alcohol misuse. During my first year, I worked closely with data from FinnTwin12, a population-based study of Finnish twins who have been followed from adolescence through young adulthood. In collaboration with the FinnTwin12 investigators, I utilized a co-twin comparison design to examine associations of a wide array of adolescent factors with alcohol misuse (1) and dependence (2). This type of design controls for genetic and environmental influences that twin siblings share, allowing us to distinguish relevant targets for preventive intervention efforts from non-causal markers of familial liability. Our findings highlighted several adolescent factors, including alcohol expectancies, academic performance, substance use, externalizing and internalizing problems, and peer deviance, as putative targets for efforts to reduce alcohol misuse and problems.\
<br/>
Throughout the course of my research in developmental psychology, I also sought opportunities to integrate genetics into my work. I cultivated my interest in biological pathways to AUD by co-leading an epigenome-wide association study of alcohol consumption (3), and I began to collaborate with Dr. Alexis Edwards at the Virginia Institute of Psychiatric and Behavioral Genetics, eventually transitioning to her lab as a graduate student in the Integrative Life Sciences – Behavioral and Statistical Genetics Ph.D. program in 2020. My work with Dr. Edwards offered the exciting opportunity to expand my research interests beyond alcohol misuse as an outcome, and I became increasingly interested in the relationship between AUD and suicidal behavior.\
<br/>
In my first project under Dr. Edwards’ mentorship, I tested the association between sibling diagnosis with AUD and one’s own risk for suicide attempt within the Swedish registries, which include medical, pharmacy, criminal, sociodemographic, and household data on the entire population of Sweden. Interestingly, we found that a sibling’s diagnosis with AUD was associated with elevated risk for suicide attempt, and suicide attempt risk declined as a function of time elapsed since the sibling’s diagnosis (4). This work provided preliminary evidence for exposure to sibling AUD as an environmental risk factor for suicide attempt, suggesting that clinical outreach may be warranted following a sibling’s diagnosis with AUD.\
<br/>
Next, I expanded my study of the complex relationship between AUD and suicidal behavior by considering the role of impulsivity. Prior research on suicidal behavior has conceptualized impulsivity in two different ways: as an individual-level personality trait associated with elevated risk for suicide attempt and as a characteristic of the attempt itself. Correspondingly, I conducted two studies investigating the relationships among substance use and problems, suicide attempt, and impulsivity. In the first study, I derived a common genetic factor representing shared genetic liability for alcohol consumption, alcohol problems, and suicide attempt. This common genetic factor was significantly correlated with all five impulsive personality traits proposed by the UPPS-P Model of Impulsive Personality (5), providing evidence for the genetic overlap between alcohol-related outcomes, suicide attempt, and features of impulsive personality (manuscript under review). In a second study, I instead considered the impulsivity of a suicide attempt, investigating associations of substance use and dependence with planned versus unplanned suicide attempts in a nationally representative sample. Although these analyses replicated previously established associations between substance-related outcomes and suicide attempt, there was little evidence that substance use and dependence were related to risk for unplanned suicidal behavior (manuscript in preparation). Taken together, these studies suggest that substance use and dependence may be more closely related to individual-level impulsivity than to the degree of planning associated with a suicide attempt.\
<br/>

**Dissertation Analyses**\
My doctoral dissertation brings together my interests in gene-environment interplay, familial relationships, impulsivity, and suicidal behavior by uniting indices of genetic liability with ideation-to-action theories of suicide. Ideation-to-action theories suggest that the primary predictor of suicide attempt among individuals experiencing suicidal ideation is their level of capability for suicide. The Interpersonal-Psychological Theory of Suicide (IPT), which is the first and perhaps most well-known ideation-to-action theory, further suggests that capability for suicide is acquired across development through exposure to physically painful and/or fear-inducing experiences, or painful and provocative events (PPEs) (6). Though exposure to PPEs is thought to play a critical role in the development of acquired capability, few studies have empirically tested the relationship between PPE exposure and risk for suicide attempt.\
<br/>
Therefore, my dissertation research aims to clarify the role of PPEs in the transition from suicidal thoughts to behaviors. First, I will apply an extension of the co-twin comparison design – the co-relative model – to investigate the degree to which associations between a comprehensive set of PPEs (e.g., painful medical conditions, injuries, trauma) and risk for suicide attempt reflect a causal effect versus confounding by genetic and familial environmental factors. Second, I will empirically test one hypothesis forwarded by the IPT: that individuals at higher genetic risk for suicide attempt demonstrate higher levels of impulsivity and are more likely to seek out PPEs. Third, I will evaluate the role of parenting behaviors in the transition from suicidal ideation to attempt in adolescence, including potential interactions among parenting, genetic liability for suicide attempt, and PPE exposure. By investigating the relationships between PPEs, genetic risk for suicide attempt, impulsivity, parenting, and suicidal behavior, these analyses (currently underway) will yield insight into the predictive utility of ideation-to-action theories and highlight relevant risk factors for the transition from suicidal thoughts to behaviors.\
<br/>
   
**Future Directions**\
As I progress in my career, I will continue to explore the roles of familial relationships and genetic risk in the development of suicidal behavior. One avenue of particular interest is to examine risk for suicide attempt and death among individuals experiencing suicide bereavement, including how risk varies based on the nature of the relationship (i.e., whether the individual who died by suicide was their child, parent, spouse, sibling, etc.), prior psychiatric history, and genetic liability for suicide attempt. In addition, though substance use is not heavily featured in my dissertation work, alcohol use and misuse remain a focus of my research. In particular, I am interested in continuing to explore the nature of the relationship between alcohol-related outcomes and suicidal behavior. As genome-wide association studies are conducted with more nuanced suicide phenotypes, this will afford the opportunity to investigate how the genetic relationship between alcohol- and suicide-related outcomes varies based on characteristics of the suicide attempt (e.g., degree of planning and preparation, method used). The motivation for and characteristics of suicidal behavior are quite heterogeneous, raising the possibility that distinct etiological pathways are also involved.\
<br/>
Ultimately, my goal is to make meaningful contributions to the literature on suicidal behavior while also engaging students as research collaborators. Importantly, the interdisciplinary nature of my research will allow me to mentor students across academic disciplines, including biology and psychology. Because I primarily conduct secondary analyses of existing datasets, some of which are publicly available, my work is also scalable; I can work with students on relatively simple, semester-long research projects or develop their abilities to apply complex statistical methods to genetic and phenotypic data over a period of years. I am enthusiastic about sharing my experiences with passionate undergraduate students through academic collaboration and research mentorship, while pursuing innovative research.\
<br/>

**References**\

1. Stephenson, M. *et al.* Which adolescent factors predict alcohol misuse in young adulthood? A co-twin comparisons study. *Addiction* **115**, 877–887 (2020).\
2. Stephenson, M. *et al.* Predicting alcohol dependence symptoms by young adulthood: A co-twin comparisons study. *Twin Res. Hum. Genet.* **24**, 204–216 (2021).\
3. Stephenson, M. *et al.* Associations of alcohol consumption with epigenome-wide DNA methylation and epigenetic age acceleration: Individual-level and co-twin comparison analyses. *Alcohol. Clin. Exp. Res.* **45**, 318–382 (2021).\
4. Stephenson, M. E. *et al.* Sibling alcohol use disorder Is associated with increased risk for suicide attempt. *Clin. Psychol. Sci.* **10**, 374–382 (2022).\
5. Whiteside, S. P. & Lynam, D. R. The Five Factor Model and impulsivity: Using a structural model of personality to understand impulsivity. *Personal. Individ. Differ.* **30**, 669–689 (2001).\
6. Joiner, T. *Why people die by suicide.* (Harvard University Press, 2005).