---
title: "Teaching Statement"
output: html_document
---
<br/>
As an undergraduate student at Washington and Lee University, I was fortunate to be immersed in a learning environment driven by the motto, “not unmindful of the future.”  Beyond providing formal instruction on topics ranging from intracellular processes to theories of interpersonal relationships, my professors guided me in selecting a career path, encouraged me to think critically, and bolstered my ability to engage in creative, impactful research. Learning activities prioritized critical thinking and applications of the material over rote memorization, and, as a learner, I developed confidence and curiosity in the classroom. Accordingly, my own approach to teaching is shaped by a focus on the future. As an instructor and mentor, my primary objectives are to (1) support comprehensive knowledge of the course material and its applications; (2) promote the development of transferable skills; and (3) foster a relational and collaborative learning environment.\
<br/>

**Overview of Teaching and Mentoring Experience**\
I have enthusiastically pursued opportunities to engage with and mentor students since pursuing an undergraduate degree myself. During my first year at Virginia Commonwealth University (VCU), I served as a graduate student mentor for *Spit for Science: Conducting and Understanding Research*. In this role, I guided a team of four undergraduate students as they selected a research question of interest to them, drafted and carried out an analytic plan, and presented their findings to the class. I immensely enjoyed the opportunity to collaborate with students who have a shared passion for research, while also engaging in broader discussions about leadership, collaboration, and potential career paths.\
<br/>
Over the next year, I built upon this initial mentorship experience through teaching assistantships with the Writing Center, Department of Focused Inquiry, and Department of Psychology. In my role as a Writing Center consultant, I assisted both graduate and undergraduate students at every stage of the writing process, from brainstorming initial ideas to refining a complete draft. In addition, I served as a teaching assistant for Focused Inquiry: a course composed entirely of first-year students that aims to build essential skills for academic success. Because Focused Inquiry is a relatively small course, with only 22 students per section, and includes one-on-one meetings with each student throughout the semester, I developed meaningful relationships with many of my students, and I greatly appreciated the opportunity to guide them through the transition to undergraduate-level work. Finally, in the Spring of 2020, I was a teaching assistant in a psychopharmacology course offered through the Department of Psychology. I assisted with the transition from in-person to virtual instruction during the onset of the COVID-19 pandemic, allowing me to gain an appreciation for the level of flexibility and creativity required in a teaching role.\
<br/>
I further developed my teaching skills and approach to instruction through my enrollment in the Preparing Future Faculty Program at VCU, which consists of both coursework and a hands-on internship experience. In the Fall of 2022, I had the opportunity to serve as a teaching intern for *Phage Hunters*, an Honors course offered through the Department of Biological Sciences at the University of Mary Washington. My internship experience was invaluable: I benefitted from the mentorship of an experienced faculty member at a liberal arts institution, and I developed my abilities in laboratory instruction. Further, I adopted a more active role in the teaching and learning process by developing assignments and leading review sessions. Each of these teaching and mentorship experiences has allowed me the opportunity to apply and amend my teaching goals.\
<br/>

**Comprehensive Knowledge of the Course Material and its Applications**\
One of my primary objectives in the classroom is to foster a deep understanding of the course material and its applications. As I transition to the role of a primary instructor, my focus on understanding, evaluation, and application will shape both my presentation of the material and assessment of knowledge. For example, in my experiences as a guest lecturer, I often structure my presentations as an overview of learning objectives and basic concepts, followed by a series of questions that allow students to, first, practice those foundational skills and then apply them to a new situation. When I discussed the structure of a speech with my Focused Inquiry students, for instance, I first presented a few slides on the components of a speech, asked them to work with a partner to recall those structural components, and, finally, invited them to evaluate the structure of several sample speeches in small groups. This practice of progressively modifying the balance between autonomy and support is grounded in self-determination theory: Scaffolding learning ensures that students rarely face intractable challenges, thereby fostering intrinsic motivation.\
<br/>

**Development of Transferable Skills**\
Given that the vast majority of students will not choose to become geneticists or statisticians, my second goal is to foster the development of transferable skills that will benefit all students, regardless of their chosen career path. In particular, I aspire for students to leave my class feeling confident in their ability to critically evaluate study design, understand and interpret statistical findings, develop and present an informed opinion to their peers, understand the meaning (and limitations) of genetic information when making health-related decisions, and engage in a professional environment. Consistent with my goal to promote transferable skills, I plan to use varied assessment strategies in each of my courses. For instance, in an introductory statistics course, assessments may include exams in which students demonstrate their foundational knowledge of the course material, short response papers and/or oral presentations in which students summarize and critically evaluate a chosen research article, and class discussions about how research findings are presented in the media. By offering a variety of methods for students to demonstrate their mastery of the material, I aim to more accurately reflect students’ unique skill sets and career interests, thereby enhancing the personal relevance of assignments.\
<br/>

**Relational and Collaborative Learning Environment**\
Finally, I strive to foster a relational and collaborative learning environment. Driven by a rich body of research on self-determination, I view student autonomy, as well as relationships with and among my students, as critical components of an effective learning environment. At the beginning of the semester, I plan to gather information about students’ academic majors, career plans, and reasons for taking the course. This information will guide my expectations for students (for example, learning nucleotide structures may be imperative for a group of students who plan to apply to medical school but trivial for a group of non-majors who are taking their required science course) and allow me to tailor course discussions to students’ interests. In addition, I hope to incorporate student input and choice in my course assignments. If I assigned a research paper within a psychiatric genetics course, for instance, I would encourage students to investigate a psychiatric disorder of particular interest to them and adapt their approach to their field of interest: A student majoring in clinical psychology may choose to highlight empirically supported targets for prevention and intervention, whereas a student majoring in history may describe the evolution of diagnostic criteria over time.\
<br/>
Accordingly, I view my relationship with students as comparable to the relationship between a builder and interior designer. As the builder, I develop the basic framework of the house: I create the blueprint, lay the foundation, erect the structure, and install the essentials. In the context of a course, I compile a list of significant readings, share foundational knowledge, and outline expectations for the classroom environment. However, as the interior designer, students can make decisions about their own learning experience, thereby transforming my empty shell to an engaging and interesting space. What are their strengths in the classroom, and what are some skills that they would like to work on? What topics are they most interested in exploring, and why?\
<br/>

**Conclusion**\
As an instructor, I hope to communicate that genetics and statistics are not merely a compilation of facts; they are ever-evolving fields with clear, and often substantial, impacts on our daily lives. Just as my undergraduate professors encouraged me to be mindful of the future, I strive to implement a collaborative approach to teaching that fosters meaningful relationships with students, promotes a comprehensive understanding of the course material, and facilitates their personal and professional success, regardless of their chosen field of study.